[package]
name = "endarke/gameanalytics-sdk"
description = "This is a forked version from the official GameAnalytics Roblox SDK. This addition is within full intention of patching immediate issues."
version = "2.2.3"
license = "MIT"
authors = ["GameAnalytics <sdk@gameanalytics.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["ExampleProject"]

[dependencies]
